### ISSUE TITLE
Plugin doesn't work with the wp super cache plugin

### ISSUE THREAD

**Issue by Wendihihi** [ecoal95/ec-stars-rating#4]
It would be great if you would manage to get this plugin working together with wp super cache. Many people use a cache plugin to speed up their website. Using a cache plugin together with your flexible rating would be a great combination.

The issue now is that you can click on a star and the vote will be registered but the votes count and stars css won't update.

**Comment by emilio** [comment]
Humm... After some thinking about this I think we have a few options:

### 1. Use Javascript

The most proper way is to fetch the data with Javascript via an AJAX call, and update the page with the correct data.

It could be opt-in, to keep the old behaviour by default, and also for those who want to sacrifice real-time ratings for getting better performance.

Pros:
- Works with any caching system.
- Not too hard to implement.

Cons:
- At least one extra HTTP request per page where a rating appears.
- SEO implications? (not probably)

### 2. Invalidate cache

This is another option. We could invalidate the pages where the post appears when a new vote is registered.

Pros:
- No extra HTTP request.

Cons:
- Depends of the caching plugin in use (if any).
- Harder (if not impossible) to implement right (the rating might appear in the homepage, in the category page, etc...).

### 3. Do nothing and rely on the theme

Some caching plugins ([WP super cache at least](https://wordpress.org/plugins/wp-super-cache/faq/)) have ways to declare a content dynamic. This hurts performance though, since pages must be served from PHP.

Pros:
- No work needed.

Cons:
- Performance hit (serving cached pages through PHP).

---

So... That said and given that the new feature will be optional (so if there are any SEO implications I could be not aware of it can be turned off), I'll be happy to implement number 1 as soon as possible.

Until I take the time to implement it, you can use number 3 if performance is not too critical.

Does that sound good too you @Wendihihi? Any other option I could have missed?

Thanks!

**Comment by emilio** [comment]
Preliminar solution in #5.

Will wait for some time for @Wendihihi's comments and if everything seems ok I'll merge it and publish it.

**Comment by Wendihihi** [comment]
Hi,

I still need to look at the solutions above. Please give me a day or two. Bit busy at the moment...

Thanks

**Comment by emilio** [comment]
Yeah, sure, don't worry :)

**Comment by Wendihihi** [comment]
For now I like option 1 and I am willing to try it out on my website. Is it enough to just replace ec-stars-rating.js to see if it does the jobe or did you also change something in ec-stars-rating.php?

I'm curious if this part of the FAQ at WP Super Cache will be possible. It's way over my head to understand it. It will be a very specific thing for WP Super Cache though...

"WP Super Cache 1.4 introduced a cacheaction filter called wpsc_cachedata. The cached page to be displayed goes through this filter and allows modification of the page. If the page contains a placeholder tag the filter can be used to replace that tag with your dynamically generated html. The function that hooks on to the wpsc_cachedata filter should be put in a file in the WP Super Cache plugins folder unless you use the late_init feature. An example plugin is included. Edit dynamic-cache-test.php to see the example code. There are two example functions there. There's a simple function that replaces a string (or tag) you define when the cached page is served. The other example function uses an output buffer to generate the dynamic content. Due to a limitation in how PHP works the output buffer code MUST run before the wpsc_cachedata filter is hit, at least for when a page is cached. It doesn't matter when serving cached pages. See this post for a more technical and longer explanation. To execute WordPress functions you must enable the 'Late init' feature on the advanced settings page."

Thanks for the modification.

**Comment by emilio** [comment]
> For now I like option 1 and I am willing to try it out on my website. Is it enough to just replace ec-stars-rating.js to see if it does the jobe or did you also change something in ec-stars-rating.php?

You should replace both the JS and PHP files.

> I'm curious if this part of the FAQ at WP Super Cache will be possible. It's way over my head to understand it. It will be a very specific thing for WP Super Cache though...
> 
> "WP Super Cache 1.4 introduced a cacheaction filter called wpsc_cachedata. The cached page to be displayed goes through this filter and allows modification of the page. If the page contains a placeholder tag the filter can be used to replace that tag with your dynamically generated html. The function that hooks on to the wpsc_cachedata filter should be put in a file in the WP Super Cache plugins folder unless you use the late_init feature. An example plugin is included. Edit dynamic-cache-test.php to see the example code. There are two example functions there. There's a simple function that replaces a string (or tag) you define when the cached page is served. The other example function uses an output buffer to generate the dynamic content. Due to a limitation in how PHP works the output buffer code MUST run before the wpsc_cachedata filter is hit, at least for when a page is cached. It doesn't matter when serving cached pages. See this post for a more technical and longer explanation
>  . To execute WordPress functions you must enable the 'Late init' feature on the advanced settings page."

I think this does not apply for our use case: This is intended to
replace something static when the cache is being created with something
dynamic, but just when the cache is being generated.

**Comment by Wendihihi** [comment]
OK, I'm going to try it out and let you know, also if I see any SEO related changes.
